In [3]:
import numpy as dsa

In [5]:
dsa.__version__

'1.26.4'

In [7]:
arr1 = dsa.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [9]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [11]:
type(arr1)

numpy.ndarray

In [13]:
arr1.shape

(9,)

In [15]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [17]:
arr1[4] 

48

In [19]:
arr1[1:4] 

array([21, 32, 43])

In [21]:
arr1[1:4+1] 

array([21, 32, 43, 48])

In [23]:
indices = [1, 2, 5, 6]

In [25]:
arr1[indices] 

array([21, 32, 15, 76])

In [27]:
mask = (arr1 % 2 == 0)

In [29]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [31]:
arr1[mask]

array([10, 32, 48, 76])

In [33]:
arr1[0] = 100

In [35]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [37]:
try:
    arr1[0] = 'Novo elemento'
except:
    print("Operação não permitida!")

Operação não permitida!


## Funçoes NumPy

In [40]:
arr2 = dsa.array([1, 2, 3, 4, 5])

In [44]:
print(arr2)

[1 2 3 4 5]


In [46]:
type(arr2)

numpy.ndarray

In [48]:
arr2

array([1, 2, 3, 4, 5])

In [50]:
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [52]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [64]:
dsa

<module 'numpy' from 'C:\\Users\\caiog\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [56]:
arr3 = dsa.arange(0, 50, 5)

In [58]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [60]:
type(arr3)

numpy.ndarray

In [66]:
dsa.shape(arr3)

(10,)

In [68]:
print(arr3.dtype)

int32


In [70]:
arr4 = dsa.zeros(10)

In [72]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [74]:
arr5 = dsa.eye(3)

In [76]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [78]:
arr6 = dsa.diag(dsa.array([1, 2, 3, 4]))

In [80]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [82]:
arr7 = dsa.array([True, False, False, True])

In [84]:
print(arr7)

[ True False False  True]


In [86]:
arr8 = dsa.array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'])

In [88]:
print(arr8)

['Linguagem Python' 'Linguagem R' 'Linguagem Julia']


A função linspace() do NumPy é usada para criar uma sequência de números igualmente espaçados dentro de um intervalo especificado. Essa função é amplamente utilizada em programação científica e matemática para gerar arrays de números para diversos fins, como gráficos, cálculos e simulações.

O método linspace (linearly spaced vector) retorna um número de valores igualmente distribuídos no intervalo especificado. 

In [90]:
print(dsa.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [92]:
print(dsa.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


A função logspace() do NumPy é usada para criar uma sequência de números igualmente espaçados em escala logarítmica dentro de um intervalo especificado. Essa função é amplamente utilizada em programação científica e matemática para gerar arrays de números para diversos fins, como gráficos, cálculos e simulações.

In [94]:
print(dsa.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]
