In [1]:
import numpy as dsa

In [2]:
dsa.__version__

'1.26.4'

In [3]:
arr1 = dsa.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [4]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(9,)

In [7]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [8]:
arr1[4] 

48

In [9]:
arr1[1:4] 

array([21, 32, 43])

In [10]:
arr1[1:4+1] 

array([21, 32, 43, 48])

In [11]:
indices = [1, 2, 5, 6]

In [12]:
arr1[indices] 

array([21, 32, 15, 76])

In [13]:
mask = (arr1 % 2 == 0)

In [14]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [15]:
arr1[mask]

array([10, 32, 48, 76])

In [16]:
arr1[0] = 100

In [17]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [18]:
try:
    arr1[0] = 'Novo elemento'
except:
    print("Operação não permitida!")

Operação não permitida!


## Funçoes NumPy

In [20]:
arr2 = dsa.array([1, 2, 3, 4, 5])

In [21]:
print(arr2)

[1 2 3 4 5]


In [22]:
type(arr2)

numpy.ndarray

In [23]:
arr2

array([1, 2, 3, 4, 5])

In [24]:
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [25]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [26]:
dsa

<module 'numpy' from 'C:\\Users\\caiog\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [27]:
arr3 = dsa.arange(0, 50, 5)

In [28]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [29]:
type(arr3)

numpy.ndarray

In [30]:
dsa.shape(arr3)

(10,)

In [31]:
print(arr3.dtype)

int32


In [32]:
arr4 = dsa.zeros(10)

In [33]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
arr5 = dsa.eye(3)

In [35]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
arr6 = dsa.diag(dsa.array([1, 2, 3, 4]))

In [37]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [38]:
arr7 = dsa.array([True, False, False, True])

In [39]:
print(arr7)

[ True False False  True]


In [40]:
arr8 = dsa.array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'])

In [41]:
print(arr8)

['Linguagem Python' 'Linguagem R' 'Linguagem Julia']


A função linspace() do NumPy é usada para criar uma sequência de números igualmente espaçados dentro de um intervalo especificado. Essa função é amplamente utilizada em programação científica e matemática para gerar arrays de números para diversos fins, como gráficos, cálculos e simulações.

O método linspace (linearly spaced vector) retorna um número de valores igualmente distribuídos no intervalo especificado. 

In [43]:
print(dsa.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [44]:
print(dsa.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


A função logspace() do NumPy é usada para criar uma sequência de números igualmente espaçados em escala logarítmica dentro de um intervalo especificado. Essa função é amplamente utilizada em programação científica e matemática para gerar arrays de números para diversos fins, como gráficos, cálculos e simulações.

In [46]:
print(dsa.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


In [47]:
arr9 = dsa.array( [ [1,2,3] , [4,5,6] ] ) 

In [48]:
type(arr9)

numpy.ndarray

In [96]:
print(arr9)

[[1 2 3]
 [4 5 6]]


In [98]:
print(arr9.shape)

(2, 3)


In [100]:
arr10 = dsa.ones((2,3))

In [102]:
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [104]:
lista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

In [106]:
arr11 = dsa.matrix(lista)

In [108]:
type(arr11)

numpy.matrix

In [110]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [112]:
dsa.shape(arr11)

(3, 3)

In [114]:
arr11.size

9

In [116]:
print(arr11.dtype)

int32


In [118]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [120]:
arr11[2,1]

48

In [122]:
arr11[0:2,2]

matrix([[22],
        [59]])

In [124]:
arr11[1,]

matrix([[ 0, 34, 59]])

In [126]:
arr11[1,0] = 100

In [128]:
print(arr11)

[[ 13  81  22]
 [100  34  59]
 [ 21  48  94]]


In [130]:
x = dsa.array([1, 2])  # NumPy decide o tipo dos dado
y = dsa.array([1.0, 2.0])  # NumPy decide o tipo dos dado
z = dsa.array([1, 2], dtype = dsa.float64)  # Forçamos um tipo de dado em particular

In [132]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [134]:
arr12 = dsa.array([[24, 76, 92, 14], [47, 35, 89, 2]], dtype = float)

In [136]:
print(arr12)

[[24. 76. 92. 14.]
 [47. 35. 89.  2.]]


O itemsize de um array numpy é um atributo que retorna o tamanho em bytes de cada elemento do array. Em outras palavras, o itemsize representa o número de bytes necessários para armazenar cada valor do array numpy.

In [139]:
arr12.itemsize

8

In [141]:
arr12.nbytes

64

In [143]:
arr12.ndim

2

### Manipulando Objetos de 3 e 4 Dimensões com NumPy

In [146]:
arr_3d = dsa.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

In [148]:
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [150]:
arr_3d.ndim

3

In [152]:
arr_3d.shape

(2, 3, 4)

In [154]:
arr_3d[0, 2, 1]

10

In [156]:
# Cria um array numpy de 4 dimensões
arr_4d = dsa.array([
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [11, 12, 13, 14, 15],
            [16, 17, 18, 19, 20]
        ],
        [
            [21, 22, 23, 24, 25],
            [26, 27, 28, 29, 30],
            [31, 32, 33, 34, 35],
            [36, 37, 38, 39, 40]
        ],
        [
            [41, 42, 43, 44, 45],
            [46, 47, 48, 49, 50],
            [51, 52, 53, 54, 55],
            [56, 57, 58, 59, 60]
        ]
    ],
    [
        [
            [61, 62, 63, 64, 65],
            [66, 67, 68, 69, 70],
            [71, 72, 73, 74, 75],
            [76, 77, 78, 79, 80]
        ],
        [
            [81, 82, 83, 84, 85],
            [86, 87, 88, 89, 90],
            [91, 92, 93, 94, 95],
            [96, 97, 98, 99, 100]
        ],
        [
            [101, 102, 103, 104, 105],
            [106, 107, 108, 109, 110],
            [111, 112, 113, 114, 115],
            [116, 117, 118, 119, 120]
        ]
    ]
])

In [158]:
print(arr_4d)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


In [160]:
arr_4d.ndim

4

In [162]:
arr_4d.shape

(2, 3, 4, 5)

In [164]:
arr_4d[0, 2, 1]

array([46, 47, 48, 49, 50])

In [166]:
arr_4d[0, 2, 1, 4]

50